title: "Daniel Sánchez Ordóñez"
description: >
  Postdoctoral Researcher, Università Roma Tre<br>
  <a href="assets/cv_SANCHEZ_ORDONEZ.pdf">📄 CV</a> |
  <a href="mailto:d.sanchez.ordonez@psemail.eu">📧 Email</a> 
logo: /assets/profile.jpeg
theme: jekyll-theme-minimal
show_downloads: false
include:
  - assets/css
