title: "Daniel Sánchez Ordóñez"
description: >
  <a href="assets/cv_SANCHEZ_ORDONEZ.pdf">📄 CV</a> |
  <a href="mailto:d.sanchez.ordonez0@gmail.com">📧 Email</a>
logo: /assets/profile.jpeg
theme: jekyll-theme-minimal
show_downloads: false
include:
  - assets/css
